// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN RUST INSTEAD.

#[allow(unused)]
use spacetimedb_sdk::{
    anyhow::{anyhow, Result},
    identity::Identity,
    reducer::{Reducer, ReducerCallbackId, Status},
    sats::{de::Deserialize, ser::Serialize},
    spacetimedb_lib,
    table::{TableIter, TableType, TableWithPrimaryKey},
    Address,
};

#[derive(Serialize, Deserialize, Clone, PartialEq, Debug)]
pub struct Character {
    pub identity: Identity,
    pub level: u16,
    pub title: Option<String>,
}

impl TableType for Character {
    const TABLE_NAME: &'static str = "Character";
    type ReducerEvent = super::ReducerEvent;
}

impl TableWithPrimaryKey for Character {
    type PrimaryKey = Identity;
    fn primary_key(&self) -> &Self::PrimaryKey {
        &self.identity
    }
}

impl Character {
    #[allow(unused)]
    pub fn filter_by_identity(identity: Identity) -> Option<Self> {
        Self::find(|row| row.identity == identity)
    }
    #[allow(unused)]
    pub fn filter_by_level(level: u16) -> TableIter<Self> {
        Self::filter(|row| row.level == level)
    }
    #[allow(unused)]
    pub fn filter_by_title(title: Option<String>) -> TableIter<Self> {
        Self::filter(|row| row.title == title)
    }
}
